spring.datasource.url=jdbc:postgresql://localhost:5432/hustlehub_payments
spring.datasource.username=postgres
spring.datasource.password=7624

app.jwt.secret=KOlEj5jroYCGgH5CB5IbEBSRoq3SkuAeH9q73LYDTA/qNUybJ3nddU5AMZsbWLaI
app.internal.key=xf/IZyAi532ky/qT09/zt9ZlY4EVuR+PV0ptIlqJ93U=
app.services.identity.url=http://localhost:8181
app.services.payments.url=http://localhost:8185

app.paystack.secret-key=sk_test_dd62d1a86f9f4f87b3bdd7f6a5b7c87f60c10001
app.paystack.callback-url=hustlehub://payment-callback

spring.jpa.show-sql=false
logging.level.com.hustlehub.payments=DEBUG
