spring.datasource.url=jdbc:postgresql://localhost:5432/hustlehub_notifications
spring.datasource.username=postgres
spring.datasource.password=7624

app.jwt.secret=KOlEj5jroYCGgH5CB5IbEBSRoq3SkuAeH9q73LYDTA/qNUybJ3nddU5AMZsbWLaI
app.internal.key=xf/IZyAi532ky/qT09/zt9ZlY4EVuR+PV0ptIlqJ93U=

spring.jpa.show-sql=false
logging.level.com.hustlehub.notifications=DEBUG
